version: '3.7'
services:
  mysql:
    image: mysql:8.0
    ports:
      - 3307:3306
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: "12345678"
      MYSQL_ROOT_USERNAME: "root" 
      MYSQL_DATABASE: "vication"
      ACCEPT_EULA: "Y"
    networks:
    - vicationet
    
  web:
    build: 
      context: ./frontend
    ports:
      - "3000:3000"

  api:
    build: 
      context: ./backend
    ports:
      - "3001:3001"
    depends_on:
      mysql:
        condition: service_started
    networks:
      - vicationet

networks:
    vicationet:
         driver: bridge
